[tool.poetry]
name = "yt-context-manger"
version = "0.1.0"
description = ""
authors = ["Damilola"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
